import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const TLDRAW_VERSION = (() => {
	const json = JSON.parse(readFileSync(`${import.meta.dirname}/node_modules/tldraw/package.json`));
	return json.version;
})();

console.log({ TLDRAW_VERSION })

// Plugin to load pdf.worker.min.mjs as text for blob URL creation
const pdfWorkerPlugin = {
	name: 'pdf-worker-text',
	setup(build) {
		build.onLoad({ filter: /pdf\.worker\.min\.mjs$/ }, async (args) => {
			const contents = readFileSync(args.path, 'utf8');
			return {
				contents: `export default ${JSON.stringify(contents)};`,
				loader: 'js',
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts", "src/styles.css"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2023",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	loader: {
		".js": "jsx",
		".woff2": "dataurl",
		".woff": "dataurl",
		".svg": "file",
		".png": "file",
		".json": "file",
	},
	outdir: ".",
	define: {
		"TLDRAW_COMPONENT_LOGGING": `${!prod}`,
		"MARKDOWN_POST_PROCESSING_LOGGING": `${!prod}`,
		"TLDRAW_VERSION": `"${TLDRAW_VERSION}"`,
	},
	plugins: [pdfWorkerPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
