import { readFileSync } from 'fs'
import process from 'process'
import path from 'node:path'
import { createEsbuildObsidianContext } from '@obsidian-plugin-toolkit/esbuild'
// import svgr from "esbuild-plugin-svgr";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const NODE_ENV = process.env.NODE_ENV
const prod = NODE_ENV === 'production'

const TLDRAW_VERSION = (() => {
	const tldrawPackageJsonPath = path.join(
		import.meta.dirname, '..', 'node_modules', 'tldraw', 'package.json'
	)
	const json = JSON.parse(readFileSync(tldrawPackageJsonPath, 'utf8'))
	return json.version
})()

const outdir = path.join(import.meta.dirname, '..', 'dist', prod ? 'production' : 'development')

// Log specific build information about the build environment
console.log({
	prod,
	TLDRAW_VERSION,
	outdir,
	NODE_ENV: process.env.NODE_ENV
})

const context = await createEsbuildObsidianContext({
	esbuildConfig: {
		banner: {
			js: banner,
		},
		entryPoints: ['src/main.ts', 'src/styles.css'],
		format: 'cjs',
		target: 'es2023',
		logLevel: 'info',
		sourcemap: prod ? false : 'inline',
		treeShaking: true,
		loader: {
			'.js': 'jsx',
		},
		outdir,
		define: {
			TLDRAW_COMPONENT_LOGGING: `${!prod}`,
			MARKDOWN_POST_PROCESSING_LOGGING: `${!prod}`,
			TLDRAW_VERSION: `"${TLDRAW_VERSION}"`,
			// Workaround for import.meta in CommonJS builds
			'import.meta': JSON.stringify({
				env: {
					TLDRAW_LICENSE_KEY: process.env.TLDRAW_LICENSE_KEY || '',
				}
			}),
		},
	},
	obsidianPluginsConfig: {
		copyManifest: {
			outdir,
			manifestSrc: path.join(import.meta.dirname, '..', 'release', 'manifest.json'),
		},
		serve: {
			port: 5173,
			host: 'localhost',
			onStartServe: async () => {
				console.log('Starting serve...')
				const serve = await context.serve({
					servedir: outdir,
				})
				return serve
			},
		},
	},
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}
